django_form/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
    path('<username>/', views.profile, name="profile"),
]

django_form/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:article_pk>/', views.detail, name="detail"),
    path('<int:article_pk>/delete/', views.delete, name="delete"),
    path('<int:article_pk>/update/', views.update, name="update"),
    path('<int:article_pk>/comments/', views.comments_create, name="comments_create"),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name="comments_delete"),
    path('<int:article_pk>/like/', views.like, name="like"),
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name="follow"),
    path('<int:hash_pk>/hashtag/', views.hashtag, name="hashtag"),
    # http://localhost:8000/search/?query=검색키워드
    path('search/', views.search, name="search"),
]

django_form/myform/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

django_form/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hashtags = models.ManyToManyField(Hashtag, blank=True)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="like_articles",
        blank=True,
    )
    
    class Meta:
        ordering = ('-pk', )

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.content

django_form/articles/forms.py
# articles/forms.py
from django import forms
from .models import Article, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label="제목",
        max_length=10,
        widget=forms.TextInput(attrs={
            'class': 'title',
            'placeholder': 'Enter the title',
        })
    )

    class Meta:
        model = Article
        fields = ('title', 'content')

# class ArticleForm(forms.Form):
#     # max_length/ min_length
#     title = forms.CharField(
#         max_length=10,
#         label="제목",
#         widget=forms.TextInput(
#             attrs={
#                 'class': 'my-title',
#                 'placeholder': 'Enter the title!',
#             }
#         )
#     )
#     content = forms.CharField(
#         min_length=20, 
#         widget=forms.Textarea(
#             attrs={
#                 'class': 'my-content',
#                 'placeholder': 'Enter the content!',
#                 'row': 5,
#                 'cols': 50,
#             }
#         )
#     )

django_form/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from IPython import embed
import hashlib

# Create your views here.
def index(request):
    articles = Article.objects.all()
    paginator = Paginator(articles, 3) # 한 페이지에 몇 개 보여줄지 설정
    page = request.GET.get("page") # 페이지 번호
    articles = paginator.get_page(page) # 해당 번호의 페이지에서 게시글 가져오기

    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


# 이런 식으로도 사용 가능하다! @login_required(login_url="/accounts/test/")
@login_required
def create(request):
    if request.method == "POST":
        # 폼 인스턴스를 생성하고 요청에 의한 데이터로 채운다. (binding)
        form = ArticleForm(request.POST)
        # 폼이 유효한지 체크한다.
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            messages.success(request, '게시글이 성공적으로 작성되었습니다!')
            # hashtag
            for word in article.content.split():
                if word.startswith("#"):
                    hashtag, created = Hashtag.objects.get_or_create(content=word)
                    article.hashtags.add(hashtag)
            return redirect("articles:detail", article.pk)
    else:
        form = ArticleForm()
    context = {'form': form}
    return render(request, 'articles/create.html', context)


def detail(request, article_pk):
    # article = Article.objects.get(pk=article_pk)
    article = get_object_or_404(Article, pk=article_pk)
    comments = Comment.objects.filter(article=article)
    person = get_object_or_404(get_user_model(), pk=article.user_id)
    comment_form = CommentForm()
    context = {
        'article': article, 
        'comment_form': comment_form, 
        'comments': comments,
        'person': person,
    }
    return render(request, 'articles/detail.html', context)


@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if request.user == article.user:
            article.delete()
        return redirect("articles:index")
    return HttpResponse('You are Unauthorized', status=401)


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if request.method == "POST":
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                article = form.save()
                # hashtag
                article.hashtags.clear()
                for word in article.content.split():
                    if word.startswith("#"):
                        hashtag, created = Hashtag.objects.get_or_create(content=word)
                        article.hashtags.add(hashtag)
                return redirect("articles:detail", article_pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect("articles:index")
    context = {'form': form}
    return render(request, 'articles/create.html', context)

@require_POST
def comments_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user # 댓글 작성한 사용자 저장
            comment.article = article
            comment.save()
        return redirect("articles:detail", article_pk)
    return HttpResponse('You are Unauthorized', status=401)

@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect("articles:detail", article_pk)


def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    user = request.user # 요청을 보낸 유저
    
    # 해당 게시글에 좋아요를 누른 사람들 중에
    # user.pk를 가진 유저가 존재하면,
    if request.user.is_authenticated:
        if article.like_users.filter(pk=user.pk).exists():
            # user를 삭제하고 (좋아요를 취소)
            article.like_users.remove(user)
            liked = False
        else:
            article.like_users.add(user)
            liked = True
        context = {'liked': liked,}
        return JsonResponse(context)
    return redirect("accounts:login")


@login_required
def follow(request, article_pk, user_pk):
    # 게시글 유저
    you = get_object_or_404(get_user_model(), pk=user_pk)
    # 현재 접속 유저
    me = request.user
    if you != me:
        if you.followers.filter(pk=me.pk).exists():
            you.followers.remove(me)
        else:
            you.followers.add(me)
    return redirect("articles:detail", article_pk)


def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    articles = hashtag.article_set.order_by("-pk")
    context = {'hashtag': hashtag, 'articles': articles}
    return render(request, 'articles/hashtag.html', context)


def search(request):
    # 사용자 검색어 추출
    query = request.GET.get("query")
    # 제목 또는 내용에서 검색어를 포함하는 게시글 가져오기
    # from django.db.models import Q
    articles = Article.objects.filter(
        Q(title__icontains=query) | Q(content__icontains=query)
    )
    
    # 페이지네이션 코드
    paginator = Paginator(articles, 3)
    page = request.GET.get("page")
    articles = paginator.get_page(page)

    context = {'articles': articles}
    return render(request, 'articles/search.html', context)

django_form/articles/templates/articles/_article.html
<!-- articles/_article.html -->

<div class="card text-center mb-5">
    <div class="card-header">
        글 작성자: {{ article.user }}
    </div>
    <div class="card-body">
        <h5 class="card-title">글 제목: {{ article.title }}</h5>
        <p class="card-text">
            {% if user in article.like_users.all %}
                <i class="fas fa-heart like-button" data-id="{{ article.pk }}" style="color: red"></i>
            {% else %}
                <i class="far fa-heart like-button" data-id="{{ article.pk }}" style="color: cadetblue"></i>
            {% endif %}
            {{ article.like_users.all|length }}명이 이 글을 좋아합니다.<br>
            <a href="{% url 'articles:detail' article.pk %}">[DETAIL]</a>
        </p>
    </div>
</div>

django_form/articles/templates/articles/_follow.html
<!-- articles/_follow.html -->

<div class="jumbotron">
    <h1 class="display-4">{{ person.username }}</h1>
    {% with followees=person.followees.all followers=person.followers.all %}
    <p class="lead">
        팔로잉: {{ followees|length }}/ 팔로워: {{ followers|length }}
    </p>
    {% if user != article.user %}
        {% if user in followers %}
            <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">Unfollow</a>
        {% else %}
            <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">follow</a>
        {% endif %}
    {% endif %}
    {% endwith %}
</div>

django_form/articles/templates/articles/_nav.html
{% load gravatar %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top"
    style="background: rgba(102, 160, 145, 1) !important;">
    {% if user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'articles:index' %}">
        <img src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?d=wavatar&s=30"
            class="d-inline-block align-top" alt="">
        Hello, {{ user.username }}
    </a>
    <form action="{% url 'articles:search' %}" class="d-flex mr-2">
        <input class="form-control mr-1" type="text" name="query" placeholder="제목 및 내용을 입력해주세요.">
        <input class="btn d-inline-block search-btn" type="submit" value="search">
    </form>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:profile' user.username %}">내프로필</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:update' %}">정보수정</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:change_password' %}">비번변경</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
            </li>
            <li class="nav-item">
                <form action="{% url 'accounts:delete' %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="회원탈퇴" class="btn btn-danger">
                </form>
            </li>
        </ul>
    </div>

    {% else %}
    <a class="navbar-brand" href="{% url 'articles:index' %}">
        <img src="https://s.https://www.gravatar.com/avatar/{{ user.email|makemd5 }}?d=wavatar" alt="">
        Hello, Stranger.
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
            </li>
        </ul>
    </div>
    {% endif %}

</nav>

django_form/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    {% if request.resolver_match.url_name == 'create' %}
    <h1>CREATE</h1>
    {% else %}
    <h1>UPDATE</h1>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %}
        <!-- form 모듈 사용 -->
        {% bootstrap_form form %}
        {% buttons submit="Submit" reset="Cancel" %}{% endbuttons %}
        <!-- 기존 방식 -->
        <!-- <input type="text" name="title">
        <input type="text" name="content"> -->
    </form>
{% endblock %}

django_form/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load make_link %}

{% block body %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <h1>DETAIL</h1>
    <hr>
    <p>글 번호: {{ article.pk }}</p>
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article|hashtag_link|safe }}</p>
    <p>글 생성 시각: {{ article.created_at|date:"SHORT_DATE_FORMAT" }}</p>
    <p>글 수정 시각: {{ article.updated_at|date:"M, j, Y" }}</p>
    {% if request.user == article.user %}
    <a href="{% url 'articles:update' article.pk %}">[UPDATE]</a>
    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>
    {% endif %}
    <hr>
    <!-- 댓글 (비로그인시 작성 제한) -->
    {% if user.is_authenticated %}
        <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
            {% csrf_token %}
            {{ comment_form }}
            <input type="submit" value="submit">
        </form>
    {% else %}
        <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인을 해주세요.]</a>
    {% endif %}
    <hr>
    <p>댓글 목록</p>
    {% for comment in article.comment_set.all %}
        <div>
            댓글 : {{ comment.content }}
            {% if user == comment.user %}
                <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="DELETE">
                </form>
            {% endif %}
        </div>
    {% endfor %}
    <hr>
    {% include 'articles/_follow.html' %}
    <hr>
    <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock %}

django_form/articles/templates/articles/hashtag.html
{% extends 'base.html' %}

{% block body %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">{{ hashtag.content }}</h1>
        <p class="lead">{{ articles|length }} 개의 게시글</p>
    </div>
</div>
<hr>
<h3>{{ hashtag.content }}를 게시한 글</h3>
<div class="row">
    {% for article in articles %}
        <div class="col-4 my-2">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <P class="card-text">{{ article.like_users.all|length }}명이 좋아요.</P>
                    <P class="card-text">{{ article.comment_set.all|length }} 개의 댓글.</P>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

django_form/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block body %}
    <h1>Articles</h1>
    {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}">[NEW]</a>
    {% else %}
    <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인을 해주세요!]</a>
    {% endif %}
    
    {% for article in articles %}
        {% include 'articles/_article.html' %}
    {% endfor %}
    <div class="d-flex justify-content-center">
        {% bootstrap_paginate articles %}
    </div>

    <script>
        // 1. 각 게시글 별로 좋아요 버튼이 있으니 All로 다 가져와보자
        const likeButtons = document.querySelectorAll('.like-button')
        
        likeButtons.forEach(button => {
            button.addEventListener('click', function(e){
                const articleId = e.target.dataset.id
                axios.defaults.xsrfCookieName = 'csrftoken'
                axios.defaults.xsrfHeaderName = 'X-CSRFToken'
                axios.post(`/articles/${articleId}/like/`)
                    .then(res => {
                        if (res.data.liked) {
                            e.target.style.color = 'crimson'
                        } else {
                            e.target.style.color = 'black'
                        }
                    })
                    .catch(err => {
                        console.log(err)
                    })
            })
        })

    </script>
{% endblock %}

django_form/articles/templates/articles/search.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}

{% block body %}
    <h1>Search Result</h1>
    {% for article in articles %}
        {% include 'articles/_article.html' %}
    {% endfor %}
    <div class="d-flex justify-content-center">
        {% bootstrap_paginate articles %}
    </div>
{% endblock %}